-- Limpiar tablas si ya existían (para evitar error "already exists")
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.metas CASCADE;

-- 1. Crear Tabla de Transacciones
CREATE TABLE public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL,
    moneda TEXT NOT NULL,
    categoria TEXT,
    monto NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Habilitar RLS para transacciones
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir select total en transacciones" 
ON public.transactions FOR SELECT USING (true);

CREATE POLICY "Permitir insert total en transacciones" 
ON public.transactions FOR INSERT WITH CHECK (true);

-- 2. Crear Tabla de Metas
CREATE TABLE public.metas (
    id TEXT PRIMARY KEY,
    current_val NUMERIC NOT NULL DEFAULT 0,
    total_val NUMERIC NOT NULL
);

-- Habilitar RLS para metas
ALTER TABLE public.metas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir select metas" 
ON public.metas FOR SELECT USING (true);

CREATE POLICY "Permitir update metas" 
ON public.metas FOR UPDATE USING (true);

CREATE POLICY "Permitir insert metas" 
ON public.metas FOR INSERT WITH CHECK (true);

-- 3. Inicializar datos por defecto para las Metas
INSERT INTO public.metas (id, current_val, total_val) 
VALUES ('meta1', 0, 65000), ('meta2', 0, 40000)
ON CONFLICT (id) DO NOTHING;
